notifications:
  email: false
sudo: false
language: ruby
rvm:
  - 2.2.2
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
env:
  global:
    - RAILS_ENV=test
    - DATABASE_URL=postgres://postgres@localhost/travis_ci_test
services:
  - postgresql
  
script: "bundle exec rake assets:precompile"
